import js from "@eslint/js";
import { defineConfig } from "eslint/config";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";
import selisI18n from "./tools/eslint/no-hardcoded-strings.ts";

export default defineConfig(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/dist-mock/**",
      "**/target/**",
      "**/gen/**",
      "**/coverage/**",
      "**/playwright-report/**",
      "**/test-results/**",
      "packages/fixtures/out/**",
      // Local scratch dir (also TMP for tooling, e.g. jiti's cache).
      ".tmp/**",
      // Generated by tauri-specta; verified for drift in CI instead.
      "apps/app/src/lib/ipc/bindings.ts",
    ],
  },
  js.configs.recommended,
  tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        project: [
          "./tsconfig.json",
          "./apps/app/tsconfig.json",
          "./apps/app/tsconfig.node.json",
          "./packages/engine/tsconfig.json",
          "./packages/engine/tsconfig.worker.json",
          "./packages/fixtures/tsconfig.json",
          "./packages/ui/tsconfig.json",
        ],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-unnecessary-condition": ["error", { allowConstantLoopConditions: true }],
      "no-restricted-syntax": [
        "error",
        { selector: "MemberExpression[property.name='then']", message: "Use async/await instead of .then chains." },
      ],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            { group: ["pdf-lib", "pdf-lib/*", "mupdf", "mupdf/*", "pdfjs-dist", "pdfjs-dist/*"], message: "Forbidden PDF library (see CLAUDE.md)." },
          ],
        },
      ],
    },
  },
  {
    files: ["apps/app/src/**/*.{ts,tsx}", "packages/ui/src/**/*.{ts,tsx}"],
    ...reactHooks.configs.flat.recommended,
  },
  {
    files: ["apps/app/src/**/*.tsx", "packages/ui/src/**/*.tsx"],
    plugins: { "selis-i18n": selisI18n },
    rules: { "selis-i18n/no-hardcoded-strings": "error" },
  },
  {
    // The UI talks to the filesystem/network only through lib/api.ts (over lib/ipc) and lib/files.ts.
    files: ["apps/app/src/**/*.{ts,tsx}"],
    ignores: ["apps/app/src/lib/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "@tauri-apps/api/core", message: "Use lib/api.ts (typed, generated IPC)." },
            { name: "@tauri-apps/plugin-dialog", message: "Use lib/files.ts." },
          ],
          patterns: [{ group: ["@embedpdf/*"], message: "Only packages/engine talks to EmbedPDF." }],
        },
      ],
    },
  },
  {
    files: ["**/*.test.{ts,tsx}", "apps/app/e2e/**/*.ts"],
    rules: {
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-floating-promises": "off",
    },
  },
);
