// @generated by tauri-specta from apps/app/src-tauri. Do not edit.
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Imports the file the user picked (a filesystem path on desktop, a
	 *  `content://` URI from the Storage Access Framework on Android, a file URL on
	 *  iOS) by copying it into the app library. The source is opened read-only.
	 * 
	 *  `name` is the sender's file name when known (Android "Open with" / share);
	 *  otherwise the title is derived from the source.
	 * 
	 *  Runs once per `request_id`: a repeated call returns the first call's result
	 *  (see `take_result`).
	 */
	importDocument: (requestId: string, source: string, name: string | null) => typedError<ImportOutcome, CommandError>(__TAURI_INVOKE("import_document", { requestId, source, name })),
	/**  Library listing: title search, filter (all / favorites / received / opened, tag) and sort. */
	listDocuments: (query: LibraryQuery) => typedError<Document[], CommandError>(__TAURI_INVOKE("list_documents", { query })),
	/**
	 *  Resolves a library document to its stored copy for the viewer.
	 *  The returned path is readable through the asset protocol (library dir only).
	 */
	readDocument: (id: string) => typedError<DocumentFile, CommandError>(__TAURI_INVOKE("read_document", { id })),
	/**
	 *  Saves page count (and the PDF's own title when the file name was unusable)
	 *  once the engine has opened the document.
	 */
	recordDocumentInfo: (id: string, pageCount: number, pdfTitle: string | null) => typedError<Document, CommandError>(__TAURI_INVOKE("record_document_info", { id, pageCount, pdfTitle })),
	/**  Idempotent: sets the flag, does not toggle it. */
	setFavorite: (id: string, favorite: boolean) => typedError<Document, CommandError>(__TAURI_INVOKE("set_favorite", { id, favorite })),
	/**
	 *  Resolves the stored copy without marking the document as opened
	 *  (used to render its thumbnail in the background).
	 */
	documentFile: (id: string) => typedError<DocumentFile, CommandError>(__TAURI_INVOKE("document_file", { id })),
	/**
	 *  Stores the page-1 thumbnail (WebP, or PNG/JPEG where the WebView cannot
	 *  encode WebP) rendered by the engine worker. Idempotent per document.
	 */
	saveThumbnail: (id: string, image: number[]) => typedError<Document, CommandError>(__TAURI_INVOKE("save_thumbnail", { id, image })),
	listTags: () => typedError<Tag[], CommandError>(__TAURI_INVOKE("list_tags")),
	/**  Returns the existing tag when one with the same (folded) name exists. */
	createTag: (name: string) => typedError<Tag, CommandError>(__TAURI_INVOKE("create_tag", { name })),
	renameTag: (id: string, name: string) => typedError<Tag, CommandError>(__TAURI_INVOKE("rename_tag", { id, name })),
	deleteTag: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_tag", { id })),
	/**  Replaces the document's tag set (idempotent). */
	setDocumentTags: (documentId: string, tagIds: string[]) => typedError<Document, CommandError>(__TAURI_INVOKE("set_document_tags", { documentId, tagIds })),
	/**  Documents waiting to be imported, oldest first. */
	pendingOpens: () => typedError<PendingOpen[], CommandError>(__TAURI_INVOKE("pending_opens")),
	/**  Called once a pending document has been imported (or failed for good). */
	dismissOpen: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("dismiss_open", { id })),
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (patch: SettingsPatch) => typedError<Settings, CommandError>(__TAURI_INVOKE("update_settings", { patch })),
	/**  Total device RAM, used by the UI to pick render limits (resolution, cache size). */
	deviceMemory: () => typedError<DeviceMemory, CommandError>(__TAURI_INVOKE("device_memory")),
	/**
	 *  Opens the system picker for one PDF. Cancel (or a picker failure) yields
	 *  `Cancelled`. Runs once per `request_id`.
	 */
	pickPdf: (requestId: string) => typedError<PickOutcome, CommandError>(__TAURI_INVOKE("pick_pdf", { requestId })),
	/**
	 *  The state of a long-running request: still running, its final result, or
	 *  unknown (never received, or expired). Read-only; a fresh call the UI makes
	 *  when the original reply did not arrive.
	 */
	takeResult: (requestId: string) => typedError<TakeResult, CommandError>(__TAURI_INVOKE("take_result", { requestId })),
};

/* Types */
export type CommandError = {
	code: ErrorCode,
	/**  Developer-facing detail, never shown verbatim to users. */
	message: string,
};

export type DeviceMemory = {
	/**  Total RAM visible to the OS, in bytes (below the marketed size). */
	totalBytes: number,
	source: MemorySource,
};

/**  A library entry as exposed to the UI. */
export type Document = {
	id: string,
	/**  Empty when no usable name is known; the UI shows a localized "Untitled". */
	title: string,
	kind: DocumentKind,
	blake3: string,
	sizeBytes: number,
	pageCount: number | null,
	/**  Unix epoch milliseconds (exported to TypeScript as `number`; < 2^53). */
	createdAt: number,
	modifiedAt: number,
	lastOpenedAt: number | null,
	favorite: boolean,
	/**  Arrived from another device (P3 transfer), as opposed to a local import. */
	received: boolean,
	/**  Sorted tag ids. */
	tagIds: string[],
	/**  Absolute path of the cached page-1 thumbnail (asset protocol), if any. */
	thumbnailPath: string | null,
	/**  Zero-based page the reader was on when the document was last closed. */
	lastPage: number | null,
};

/**  Resolved file for viewing. `path` is absolute and inside the library directory. */
export type DocumentFile = {
	document: Document,
	path: string,
};

export type DocumentKind = "imported" | "linked";

/**  Machine-readable error category; the UI maps it to a localized message. */
export type ErrorCode = "notPdf" | "emptyFile" | "notFound" | "io" | "invalidArgument" | 
/**  The name (e.g. of a tag) is already taken. */
"conflict" | 
/**  The operation did not finish in time (nothing was written). */
"timeout" | "internal";

export type ImportOutcome = {
	document: Document,
	/**  True when an identical file (same BLAKE3) was already in the library. */
	duplicate: boolean,
};

/**  Which documents a library listing contains. */
export type LibraryFilter = "all" | "favorites" | "received" | 
/**  Opened at least once (the Recent tab). */
"opened";

export type LibraryQuery = {
	/**  Title search: case-, accent- and final-sigma-insensitive substring. Empty = all. */
	search?: string,
	filter?: LibraryFilter,
	/**  Only documents carrying this tag. */
	tagId?: string | null,
	sort?: LibrarySort,
};

export type LibrarySort = 
/**  Latest activity first: opened or imported, whichever is newer. */
"recent" | 
/**  Title A→Z (folded); untitled documents last. */
"name" | 
/**  Largest first. */
"size" | 
/**  Most recently opened first (the Recent tab). */
"lastOpened";

export type LibraryView = "grid" | "list";

export type LocalePref = "system" | "el" | "en";

export type MemorySource = 
/**  Android `ActivityManager.MemoryInfo.totalMem`. */
"activityManager" | 
/**  `sysinfo` (desktop). */
"sysinfo" | 
/**  iOS `NSProcessInfo.physicalMemory`. */
"processInfo";

export type PendingOpen = {
	id: string,
	/**  `content://` URI (Android) or `file://` URL (iOS), passed to `import_document`. */
	source: string,
	/**  The sender's file name, when it told us. */
	name: string | null,
};

export type PickOutcome = { status: "picked"; source: string } | { status: "cancelled" };

export type Settings = {
	locale: LocalePref,
	theme: ThemePref,
	librarySort: LibrarySort,
	libraryView: LibraryView,
};

/**  Partial update; `None` fields are left unchanged. */
export type SettingsPatch = {
	locale: LocalePref | null,
	theme: ThemePref | null,
	librarySort: LibrarySort | null,
	libraryView: LibraryView | null,
};

/**
 *  A command's final result in the same shape the TypeScript bindings use for
 *  `Result<T, CommandError>`.
 */
export type StoredResult = { status: "ok"; 
/**  The command's own result type; the UI knows which command it called. */
data: unknown } | { status: "error"; error: CommandError };

export type Tag = {
	id: string,
	name: string,
	documentCount: number,
};

/**  Answer of `take_result`. */
export type TakeResult = 
/**  The command is still running. */
{ status: "pending" } | 
/**  The command finished; this is what its reply carried. */
{ status: "done"; result: StoredResult } | 
/**  Never seen (the call did not reach Rust) or already expired. */
{ status: "unknown" };

export type ThemePref = "system" | "light" | "dark" | "sepia";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

