// @generated by tauri-specta from apps/app/src-tauri. Do not edit.
/* eslint-disable */

// Placeholder written to the tauri-specta output contract; overwritten by
// `cargo test -p selis-app export_bindings`.

export const commands = {
  async importDocument(source: string): Promise<Result<ImportOutcome, CommandError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("import_document", { source }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async listDocuments(): Promise<Result<Document[], CommandError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("list_documents") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async readDocument(id: string): Promise<Result<DocumentFile, CommandError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("read_document", { id }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async recordDocumentInfo(id: string, pageCount: number, pdfTitle: string | null): Promise<Result<Document, CommandError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("record_document_info", { id, pageCount, pdfTitle }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async getSettings(): Promise<Result<Settings, CommandError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("get_settings") };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async updateSettings(patch: SettingsPatch): Promise<Result<Settings, CommandError>> {
    try {
      return { status: "ok", data: await TAURI_INVOKE("update_settings", { patch }) };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

export type CommandError = { code: ErrorCode; message: string };
export type Document = {
  id: string;
  title: string;
  kind: DocumentKind;
  blake3: string;
  sizeBytes: number;
  pageCount: number | null;
  createdAt: number;
  modifiedAt: number;
  lastOpenedAt: number | null;
  favorite: boolean;
};
export type DocumentFile = { document: Document; path: string };
export type DocumentKind = "imported" | "linked";
export type ErrorCode = "notPdf" | "emptyFile" | "notFound" | "io" | "invalidArgument" | "internal";
export type ImportOutcome = { document: Document; duplicate: boolean };
export type LocalePref = "system" | "el" | "en";
export type Settings = { locale: LocalePref; theme: ThemePref };
export type SettingsPatch = { locale: LocalePref | null; theme: ThemePref | null };
export type ThemePref = "system" | "light" | "dark" | "sepia";

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";

export type Result<T, E> = { status: "ok"; data: T } | { status: "error"; error: E };
