// @generated by tauri-specta from apps/app/src-tauri. Do not edit.
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Imports the file the user picked (a filesystem path on desktop, a
	 *  `content://` URI from the Storage Access Framework on Android, a file URL on
	 *  iOS) by copying it into the app library. The source is opened read-only.
	 */
	importDocument: (source: string) => typedError<ImportOutcome, CommandError>(__TAURI_INVOKE("import_document", { source })),
	listDocuments: () => typedError<Document[], CommandError>(__TAURI_INVOKE("list_documents")),
	/**
	 *  Resolves a library document to its stored copy for the viewer.
	 *  The returned path is readable through the asset protocol (library dir only).
	 */
	readDocument: (id: string) => typedError<DocumentFile, CommandError>(__TAURI_INVOKE("read_document", { id })),
	/**
	 *  Saves page count (and the PDF's own title when the file name was unusable)
	 *  once the engine has opened the document.
	 */
	recordDocumentInfo: (id: string, pageCount: number, pdfTitle: string | null) => typedError<Document, CommandError>(__TAURI_INVOKE("record_document_info", { id, pageCount, pdfTitle })),
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (patch: SettingsPatch) => typedError<Settings, CommandError>(__TAURI_INVOKE("update_settings", { patch })),
	/**  Total device RAM, used by the UI to pick render limits (resolution, cache size). */
	deviceMemory: () => typedError<DeviceMemory, CommandError>(__TAURI_INVOKE("device_memory")),
};

/* Types */
export type CommandError = {
	code: ErrorCode,
	/**  Developer-facing detail, never shown verbatim to users. */
	message: string,
};

export type DeviceMemory = {
	/**  Total RAM visible to the OS, in bytes (below the marketed size). */
	totalBytes: number,
	source: MemorySource,
};

/**  A library entry as exposed to the UI. */
export type Document = {
	id: string,
	/**  Empty when no usable name is known; the UI shows a localized "Untitled". */
	title: string,
	kind: DocumentKind,
	blake3: string,
	sizeBytes: number,
	pageCount: number | null,
	/**  Unix epoch milliseconds (exported to TypeScript as `number`; < 2^53). */
	createdAt: number,
	modifiedAt: number,
	lastOpenedAt: number | null,
	favorite: boolean,
};

/**  Resolved file for viewing. `path` is absolute and inside the library directory. */
export type DocumentFile = {
	document: Document,
	path: string,
};

export type DocumentKind = "imported" | "linked";

/**  Machine-readable error category; the UI maps it to a localized message. */
export type ErrorCode = "notPdf" | "emptyFile" | "notFound" | "io" | "invalidArgument" | "internal";

export type ImportOutcome = {
	document: Document,
	/**  True when an identical file (same BLAKE3) was already in the library. */
	duplicate: boolean,
};

export type LocalePref = "system" | "el" | "en";

export type MemorySource = 
/**  Android `ActivityManager.MemoryInfo.totalMem`. */
"activityManager" | 
/**  `sysinfo` (desktop, iOS). */
"sysinfo";

export type Settings = {
	locale: LocalePref,
	theme: ThemePref,
};

/**  Partial update; `None` fields are left unchanged. */
export type SettingsPatch = {
	locale: LocalePref | null,
	theme: ThemePref | null,
};

export type ThemePref = "system" | "light" | "dark" | "sepia";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

