//! Tauri builder, plugins and state. Commands live in `commands/` and only
//! delegate to `selis-core`. Nothing here opens a network connection.

mod commands;
mod requests;

use std::sync::Arc;

use selis_core::Library;
use tauri::Manager;
use tauri_specta::{Builder, collect_commands};

/// Single source of truth for the IPC surface. `ipc.ts` is generated from it
/// (see the `export_bindings` test).
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::library::import_document::<tauri::Wry>,
        commands::library::list_documents,
        commands::library::read_document,
        commands::library::record_document_info,
        commands::library::set_favorite,
        commands::library::set_last_page,
        commands::library::document_file,
        commands::library::save_thumbnail,
        commands::tags::list_tags,
        commands::tags::create_tag,
        commands::tags::rename_tag,
        commands::tags::delete_tag,
        commands::tags::set_document_tags,
        commands::open_with::pending_opens::<tauri::Wry>,
        commands::open_with::dismiss_open,
        commands::share::share_document::<tauri::Wry>,
        commands::settings::get_settings,
        commands::settings::update_settings,
        commands::device::device_memory::<tauri::Wry>,
        commands::picker::pick_pdf::<tauri::Wry>,
        commands::requests::take_result,
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();
    let app = tauri::Builder::default()
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(commands::open_with::init())
        .plugin(commands::share::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let root = app.path().app_data_dir()?;
            let library = Library::open(root)?;
            app.manage(Arc::new(library));
            app.manage(Arc::new(requests::RequestResults::default()));
            app.manage(Arc::new(commands::open_with::OpenQueue::default()));
            Ok(())
        })
        .build(tauri::generate_context!());
    match app {
        Ok(app) => app.run(on_run_event),
        Err(err) => {
            // Nothing sensible to recover to; surface the reason in platform logs.
            eprintln!("selis: fatal error while running the application: {err}");
            std::process::exit(1);
        }
    }
}

/// iOS (and macOS) deliver "Open in Selis" documents as file URLs here. Android
/// uses OpenWithPlugin.kt instead (tao's own intent parsing is ignored).
fn on_run_event(app: &tauri::AppHandle, event: tauri::RunEvent) {
    #[cfg(any(target_os = "ios", target_os = "macos"))]
    if let tauri::RunEvent::Opened { urls } = &event
        && let Some(queue) = app.try_state::<Arc<commands::open_with::OpenQueue>>()
    {
        for url in urls.iter().filter(|u| u.scheme() == "file") {
            queue.push(url.to_string(), None);
        }
    }
    #[cfg(not(any(target_os = "ios", target_os = "macos")))]
    let _ = (app, event);
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    /// Regenerates `apps/app/src/lib/ipc/bindings.ts`. CI fails if the committed file differs.
    #[test]
    fn export_bindings() {
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/ipc/bindings.ts");
        super::specta_builder()
            .export(
                Typescript::default()
                    .header("// @generated by tauri-specta from apps/app/src-tauri. Do not edit.\n/* eslint-disable */"),
                &path,
            )
            .expect("failed to export TypeScript bindings");
    }
}
