//! Tauri builder, plugins and state. Commands live in `commands/` and only
//! delegate to `selis-core`. Nothing here opens a network connection.

mod commands;

use std::sync::Arc;

use selis_core::Library;
use tauri::Manager;
use tauri_specta::{Builder, collect_commands};

/// Single source of truth for the IPC surface. `ipc.ts` is generated from it
/// (see the `export_bindings` test).
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::library::import_document::<tauri::Wry>,
        commands::library::list_documents,
        commands::library::read_document,
        commands::library::record_document_info,
        commands::settings::get_settings,
        commands::settings::update_settings,
        commands::device::device_memory::<tauri::Wry>,
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();
    let result = tauri::Builder::default()
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let root = app.path().app_data_dir()?;
            let library = Library::open(root)?;
            app.manage(Arc::new(library));
            Ok(())
        })
        .run(tauri::generate_context!());
    if let Err(err) = result {
        // Nothing sensible to recover to; surface the reason in platform logs.
        eprintln!("selis: fatal error while running the application: {err}");
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    /// Regenerates `apps/app/src/lib/ipc.ts`. CI fails if the committed file differs.
    #[test]
    fn export_bindings() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/lib/ipc.ts");
        super::specta_builder()
            .export(
                Typescript::default()
                    .header("// @generated by tauri-specta from apps/app/src-tauri. Do not edit.\n/* eslint-disable */"),
                &path,
            )
            .expect("failed to export TypeScript bindings");
    }
}
